/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java2c */

#ifndef _Included_Java2c
#define _Included_Java2c
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java2c
 * Method:    int_func_int
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Java2c_int_1func_1int
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
